import Link from "next/link";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div>{children}</div>
        <a href="/login">로그인</a>
        <Link href={/login}>로그인</Link>
      </body>
    </html>
  );
}
