import Link from "next/link";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const posts = await (await fetch("http://localhost:4000/posts")).json();

  return (
    <html lang="en">
      <body>
        <div>
          <Link href="/a" style={{ marginRight: "10px" }}>
            /a
          </Link>
          <Link href="/b">/b</Link>
        </div>
        <h1>Root Layout</h1>
        <pre>{JSON.stringify(posts, null, 2)}</pre>
        {children}
      </body>
    </html>
  );
}
