import Link from "next/link";
import "./globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <div>
          <Link href="/">Home</Link>
          &nbsp; &nbsp;
          <Link href="/about">About</Link>
        </div>
      </body>
    </html>
  );
}
